### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [sirebellum/qgis-segmentation#1]
Please fix the plugin homepage in metadata.txt
![image](https://github.com/sirebellum/qgis-segmentation/assets/2510900/0fdd4941-05f6-4f0d-8e54-346055bf19ad)

**Comment by sirebellum** [comment]
Uploaded new plugin with correct metadata.

**Comment by NyakudyaA** [comment]
Please upload a new plugin

**Comment by NyakudyaA** [comment]
@sirebellum Please change the plugin homepage to this repo, the link needs to be informative, rather put https://github.com/sirebellum/qgis-segmentation/blob/main/README.md
