### ISSUE TITLE
ValueError: cannot reshape array of size 24425104 into shape (4,324,8,294,8)

### ISSUE THREAD

**Issue by jducnuigeen** [sirebellum/qgis-segmentation#17]
I've tried the tool on a small raster:
Extent	1245766.2999999877065420,4850525.0999999521300197 : 1245883.7499999876599759,4850654.5499999513849616
Width	2349
Height	2589
Data type	Byte - Eight bit unsigned integer
GDAL Driver Description	GTiff
GDAL Driver Metadata	GeoTIFF
I don't have a dedicated GPU, so it will use CPU apparently.
When I run the tool against this, I get the error:
`2024-09-03T13:19:32     WARNING    Traceback (most recent call last):
              File "/home/jan/.local/share/QGIS/QGIS3/profiles/Jan1/python/plugins/qgis-segmentation/segmenter.py", line 425, in predict
              coverage_map = self.predict_kmeans(
              File "/home/jan/.local/share/QGIS/QGIS3/profiles/Jan1/python/plugins/qgis-segmentation/segmenter.py", line 221, in predict_kmeans
              array_2d = array_padded.reshape(
             ValueError: cannot reshape array of size 24425104 into shape (4,324,8,294,8)
             `

**Comment by sirebellum** [comment]
Hey there, thanks for opening an issue. So I can reproduce the issue, could you attach a copy of the raster you are trying to process to this ticket?

**Comment by jducnuigeen** [comment]
[lds-invercargill-005m-urban-aerial-photos-2022-GTiff.zip](https://github.com/user-attachments/files/16857751/lds-invercargill-005m-urban-aerial-photos-2022-GTiff.zip)
Sure, hopefully it is not too large to upload.

**Comment by sirebellum** [comment]
It looks like there are 4 bands in the raster. The 4th band is alpha (first three are rgb). The tool expects a 3 band rgb raster without an alpha band. Please remove the alpha band via toolbox -> rearrange bands.

I've also pushed an update to the plugin that was creating an issue with that specific raster size.

**Comment by jducnuigeen** [comment]
Great, thank you for catching that and the update ! I pulled down the latest version, and I've converted to 3 band, and now at least the K-means works.
Unfortunately with K-means it can't differentiate between the green roof and the street, or between the different shading on the same roof, even if I get upwards of 8 or 10 segments.
I'm not sure what I can do to improve that distinction.
My main goal is to differentiate the roof areas from everything else. Not easy for sure, since roofs can be so many colours, shapes, and shading, and can be so similar to sealed roads.
I tried CNN, but it causes QGIS to crash completely with no error supplied.
I'm on Ubuntu 22.04, QGIS 3.34

**Comment by sirebellum** [comment]
Hey there! Sorry for the late reply, this is a side project for me and doesn't receive the time it should.
I'm sorry to hear the CNN mode is crashing your computer. Try dumping the contents of the below directory to see if we can diagnose.
`$HOME/.local/share/QGIS/QGIS3/profiles/default/logs/`

Edit: Make sure to try with the latest plugin version.
